# Generated by Django 3.1.7 on 2021-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_0615'),
        ('api', '0002_challenges_render_img'),
    ]

    operations = [
    ]
